name: Bump Homebrew Cask versions
on:
  schedule:
    # Every third day at 8:00 on GMT+2
    - cron: '0 6 */3 * *'
  workflow_dispatch:

permissions:
  pull-requests: write
  # Allows creating branches
  contents: write

# Automatic token from Github when using permissions: directive above
# This allows us to create PRs to the repository and to avoid
# "GitHub API Error: API rate limit exceeded for ..." errors
env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  bump-cask-versions:
    strategy:
      matrix:
        brew_cask: [kitsas, forscan]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Tap this repository
        run: brew tap "${{ github.repository }}"

      - name: Check if new version is available
        id: new_version
        run: |
          TAP_VERSION_INFO=$(brew livecheck --quiet --cask --newer-only --json "${{ github.repository }}/${{ matrix.brew_cask }}")
          echo "$TAP_VERSION_INFO"
          VERSION=$(echo "$TAP_VERSION_INFO" | jq -r '.[0].version.latest//empty')
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Check if the PR for the new version already exists
        id: pr_already_exists
        run: |
          BRANCH="bump-${{ matrix.brew_cask }}-${{ steps.new_version.outputs.VERSION }}"
          COMMIT=$(git ls-remote --heads origin "$BRANCH" | cut -f1)
          echo "$BRANCH has latest commit: $COMMIT"
          echo "COMMIT=$COMMIT" >> "$GITHUB_OUTPUT"
      
      - if: steps.new_version.outputs.VERSION != '' && steps.pr_already_exists.outputs.COMMIT == ''
        name: Update Homebrew Cask ${{ matrix.brew_cask }} to latest version
        run: |
          brew bump-cask-pr --no-fork --no-audit --no-browse \
            --version=${{ steps.new_version.outputs.VERSION }} \
            ${{ matrix.brew_cask }}
